FROM quay.io/jupyter/minimal-notebook:ubuntu-22.04

ENV DEBIAN_FRONTEND=noninteractive
USER root

RUN apt-get update &&\
    apt-get install --no-install-recommends -y \
        gcc \
        gfortran \
        make \
        nano \
        vim \
        unzip \
        wget \
        curl \
        git \
        htop

#RUN mkdir -p /isofit_data
# RUN chown mambauser:mambauser /isofit_data
# USER mambauser
# WORKDIR /home/mambauser
RUN mkdir -p /opt/scripts
WORKDIR /opt

# Copy and install the ISOFIT environment
# note: we are now explicitly copying the isofit git repo into the image as ISOFIT
# COPY --chown=mambauser:mambauser isofit/ ISOFIT/
COPY isofit/ ISOFIT/

# Provide ISOFIT data download script
COPY scripts/dl_isofit_data.sh /opt/scripts/

# RUN mamba config prepend channels conda-forge
RUN mamba update --all --yes
# RUN mamba install --name base jupyterlab
RUN mamba create --name isofit python=3.10
RUN mamba install --name isofit --file ISOFIT/recipe/isofit.yml
RUN mamba install --name isofit --file ISOFIT/recipe/docker.yml
# RUN echo "mamba activate isofit" >> ~/.bashrc

# ENV PATH=/opt/conda/envs/isofit/bin:$PATH

# Install ISOFIT and extra files
# RUN python -m ipykernel install --user --name isofit &&\
#     pip install -e ISOFIT

RUN python -m ipykernel install --name isofit --sys-prefix &&\
    pip install -e ISOFIT

# note: here we are now skipping embedding the ISOFIT data into the image

# Jupyter needs this to access the terminal
# ENV SHELL="/bin/bash"

# Ray Dashboard port
EXPOSE 8265

RUN apt-get update &&\
    apt-get install --no-install-recommends -y \
      libnss-wrapper

RUN groupadd -g 500 admins

WORKDIR "/home/${NB_USER}"
RUN eval "$(mamba shell hook --shell bash)" &&\
    mamba activate isofit

#======================== Fix permissions for home/jovyan ============
RUN fix-permissions "/home/${NB_USER}"

# == Add custom entrypoint script for setting up individual uids======
COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["jupyterhub-singleuser"]

### EOF